# Generated by Django 2.2 on 2019-04-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=250, null=True)),
                ('name_hy', models.CharField(max_length=250, null=True)),
                ('name_en', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opus',
            fields=[
                ('opus_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title_ru', models.CharField(max_length=500)),
                ('title_hy', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500)),
                ('comment_ru', models.CharField(max_length=1000)),
                ('comment_hy', models.CharField(max_length=1000)),
                ('comment_en', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=4, null=True)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='works.Genre', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_url', models.CharField(max_length=1000)),
                ('perform_date', models.DateField(null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('opus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='works.Opus', verbose_name='Сочинение')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fname_ru', models.CharField(max_length=250)),
                ('lname_ru', models.CharField(max_length=250, null=True)),
                ('fname_hy', models.CharField(max_length=250, null=True)),
                ('lname_hy', models.CharField(max_length=250, null=True)),
                ('fname_en', models.CharField(max_length=250, null=True)),
                ('lname_en', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=250)),
                ('performance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performers', to='works.Performance', verbose_name='Исполнение')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Person', verbose_name='Исполнитель')),
            ],
        ),
        migrations.AddField(
            model_name='opus',
            name='libretto_by',
            field=models.ManyToManyField(related_name='libr_works', to='works.Person', verbose_name='Авторы либретто'),
        ),
        migrations.AddField(
            model_name='opus',
            name='lyrics_by',
            field=models.ManyToManyField(related_name='lyr_works', to='works.Person', verbose_name='Авторы текста'),
        ),
    ]
