# Generated by Django 2.2 on 2019-04-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.CharField(default='000', max_length=10, primary_key=True, serialize=False),
        ),
    ]
