# Generated by Django 2.2 on 2019-04-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20190419_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('band_id', models.CharField(default='00000', max_length=10, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000, null=True)),
                ('type_ru', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('type_hy', models.CharField(max_length=100, null=True)),
                ('name_hy', models.CharField(max_length=100, null=True)),
                ('type_en', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='performance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='location',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='performance_url',
        ),
        migrations.AddField(
            model_name='performance',
            name='audio_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='works.Person', verbose_name='Дирижер'),
        ),
        migrations.AddField(
            model_name='performance',
            name='performance_id',
            field=models.CharField(default='0000', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='performance',
            name='video_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='works.Band', verbose_name='Исполнительский коллектив'),
        ),
    ]
