# Generated by Django 2.2 on 2019-04-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20190419_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='name_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='name_hy',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='name_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
