# Generated by Django 2.2 on 2019-04-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20190419_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='opus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='works.Opus', verbose_name='Сочинение'),
        ),
    ]
