# Generated by Django 2.2 on 2019-04-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20190422_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opus',
            options={'verbose_name_plural': 'opera'},
        ),
    ]
