# Generated by Django 2.0.2 on 2019-05-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20190423_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='audio_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='works.Band', verbose_name='Исполнительский коллектив'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='works.Person', verbose_name='Дирижер'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='name_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='name_hy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='opus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='works.Opus', verbose_name='Сочинение'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='perform_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='video_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
