# Generated by Django 2.0.2 on 2019-05-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_auto_20190501_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to='works.Genre', verbose_name='Жанр'),
        ),
    ]
