# Generated by Django 2.0.2 on 2019-05-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_auto_20190504_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='comment_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='opus',
            name='comment_hy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='opus',
            name='comment_ru',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='opus',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='opus',
            name='subtitle_hy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='opus',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='opus',
            name='title_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='opus',
            name='title_hy',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
