# Generated by Django 2.0.2 on 2019-05-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_auto_20190510_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='role',
            new_name='role_ru',
        ),
        migrations.AddField(
            model_name='performer',
            name='role_en',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='performer',
            name='role_hy',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
