# Generated by Django 2.0.2 on 2019-05-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_about_bio_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About page texts'},
        ),
        migrations.AlterModelOptions(
            name='bio',
            options={'verbose_name_plural': 'Bio page texts'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home page texts'},
        ),
        migrations.AlterField(
            model_name='about',
            name='section_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='page_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='page_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
