# Generated by Django 2.0.2 on 2019-05-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_auto_20190517_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='page_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='page_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
