# Generated by Django 2.0.2 on 2019-05-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_auto_20190518_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.Genre', verbose_name='Жанр'),
        ),
    ]
