# Generated by Django 2.0.2 on 2019-06-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_auto_20190625_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='section_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
