# Generated by Django 2.0.2 on 2019-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0017_auto_20190625_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='page_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
